### PR TITLE
[macOS] Move the window if there is no title bar

### PR DESCRIPTION
**Pull request by robertgzr**
On macOS by default windows can only be moved by clicking and
dragging on the titlebar, if we spawn a window without one we
need to set the `movableByWindowBackground` property.

Partial fix for #368

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks for the PR. I'm not sure we want this behaviour by default though.

**Comment by robertgzr** [comment]
@tomaka should I add this to `WindowBuilderExt` then?

**Comment by robertgzr** [comment]
@tomaka I made this a separate `WindowBuilder` method... any comments?

**Comment by tomaka** [comment]
Thanks, looks good! I guess we could make this attribute cross-platform in the future if there's a need and a way to implement it.

Please also add an entry in `CHANGELOG.md`.

I'll leave this open for a few hours/days in case someone has something to comment.

**Comment by robertgzr** [comment]
Do you want me to squash all of that before you merge?

**Comment by tomaka** [comment]
It will be squashed when merged.

**Comment by robertgzr** [comment]
*ping*

I have something ready that is based on the changes here...
I'm just waiting for this to be merged :)

**Pull request merged**
