### PR TITLE
Update wayland-client and client-toolkit

### PR DESCRIPTION
**Pull request by trimental**
- [x] Tested on all platforms changed

A few fixes, improvements and decoration changes

### CODE REVIEW

**Comment by vberger** [comment]
These upgrates pull a few interesting things:

- soundness fixes in `wayland-client`
- fix for #597 and several improvements on the decorations look and interactions with the server, from `smithay-client-toolkit`

However, upgrading the point-releases dependencies like this is not generally necessary, as `cargo update` already pulls them as compatible versions. It would allow us to avoid having some users coming about a bug that they actually only need to run `cargo update` to get fixed, though.

**Comment by trimental** [comment]
Ah I didn’t know that 👍, I was mostly trying to get the 2.4 client toolkit fix as without it I can’t use the wayland backend

**Comment by francesca64** [comment]
I guess there'd be no harm in merging this?

**Comment by trimental** [comment]
By the sounds of it if anything broke then it would already be broken now anyway because of the updating, I didn’t know that cargo updated minor versions automatically, I left this open because I thought it wouldn’t hurt to update it anyway.

**Comment by francesca64** [comment]
Right. Merging PRs is fun anyway.

**Pull request merged**
