### PR TITLE
Update image to 0.21

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by rukai** [comment]
Note that this is a breaking change.

**Comment by nox** [comment]
Yes, that’s written in the changelog.

**Comment by vberger** [comment]
Given this is a breaking change, should this wait until eventsloop 2.0 is merged ?

**Comment by francesca64** [comment]
@Osspial are you fine with this?

**Comment by Osspial** [comment]
@francesca64 Sure, this seems fine.

**Comment by nox** [comment]
Can this be released?

**Comment by nox** [comment]
Is there anything that is blocking the releasing of that PR?

**Comment by Osspial** [comment]
@nox Sorry about the delay!

Right now, there isn't. I'm a bit hesitant to do a release right now because this is a breaking change and there aren't that many other changes going along with it, but I'd be fine with a `0.19` PR for further discussion.

**Pull request merged**
