### PR TITLE
Add ability to change the min/max size of windows at runtime

### PR DESCRIPTION
**Pull request by Osspial**
Adds the ability to change the minimum and maximum sizes of a window, even after it's been created, with `set_min_dimensions` and `set_max_dimensions` functions on the Window struct.

I've only tested this on Windows, and I'm *pretty sure* the OSX and Linux code compiles, but it's much harder for me to test them personally than it is to test the Windows code. I'll probably be able to test the Linux code in the next couple of days but I don't think I can test the OSX code personally.

### CODE REVIEW

**Comment by francesca64** [comment]
Sorry for hijacking your PR; I was originally planning to just give you a review on the X11 portions, but fixing it turned out to be more involved, and I figured you wouldn't enjoy dealing with that.

Since `WM_NORMAL_HINTS` is just a single window property containing all of the size hints, updating min/max by only setting one causes the other one to be unset, along with any other hints. This revised implementation bases the new hints off of the current value of `WM_NORMAL_HINTS`.

Some other changes:
- I removed your usage of `unwrap_or` for handling `None`, as the values used were semantically incorrect and no longer necessary for unsetting min/max.
- I used `c_int` rather than `i32`; while ICCCM specifies the latter, the Xlib code uses the former.
- I dynamically allocated `XSizeHints` using `XAllocSizeHints`, as recommended in the lead section of [the docs](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html#XSizeHints). To facilitate this, I created a wrapper struct named `XSmartPointer`.
- I changed `XSetNormalHints` to `XSetWMNormalHints`, as the former is obsolete.
- I applied all of the relevant changes above to the window building code as well.

Note that this still needs to be looked at on Wayland and OSX. While this works fine now on X11, I've found that setting the min/max to the same size tends to permanently disable resizing for me (on XFCE). If I try to change the min/max after the fact, the hints are set correctly according to xwininfo, but the window still can't be resized (occasionally, resizing is re-enabled as expected, but it's very unreliable). However, that doesn't seem to have anything to do with anything introduced here (setting them to the same size during window building causes it to happen as well, it's just we never had a way to try to change it afterwards before), and there's a chance that it's just an issue with my WM. Thus, it would be good for more people to test this on X11.

Anyway, thanks for the contribution!

**Comment by Osspial** [comment]
I got a OSX VM running, and it seems like the code works fine. Would it be possible to merge this, once the changelog conflict is resolved?

**Comment by francesca64** [comment]
@Osspial I'm in favor of that, since I don't see getting further review as likely, and both the OS X and Wayland code are straightforward and small enough that I don't see any meaningful risk of introducing technical debt.

**Comment by tomaka** [comment]
Needs a rebase and we're good to go I think.

**Comment by Osspial** [comment]
@tomaka Just rebased. Everything should be good now.

**Pull request merged**
