### PR TITLE
winit multiple windows leak macos x

### PR DESCRIPTION
**Pull request by bogdad**
Hi!

I was updating glium to the latest glutin (https://github.com/glium/glium/compare/master...bogdad:update_glutin_0.10 not finished yet) -
had to redo the fullscreen example.

While doing that found that glutin on mac does not support shared context, tried to implement shared contexts, (https://github.com/tomaka/glutin/compare/master...bogdad:context_sharing?expand=1 not finished yet),

While testing the glium full screen example on mac with shared contexts, found that if you repeatedly pressed enter to switch in and out of fullscreen window, the memory was growing very fast. seems to be this winit issue: 
https://github.com/tomaka/winit/issues/158

screen shot 2017-10-01 at 15 31 49

and here is my take on @mitchmindtree's possible solution from that issue: "
Perhaps we could solve this by switching window.setReleasedWhenClosed_(NO);'s input to YES and store a regular cocoa::base::id for the NSWindow rather than an IdRef? It seems like IdRef was added as a method to automatically clean up objects that would normally require the user to manually release them, however in this case the NSWindow could do its own cleanup when closed, so it seems IdRef should not be necessary?
" 
Just switching window:IdRef to winow:NotRealeasingIdRef seems not enough, but adding two autorelease pools and keeping the release behavior for window in DelegateRef seems to help a lot:

screenshot 2017-10-04 22 34 32

Used Instruments allocators with recording release/retain/autorelease history for NSWindow instances to find the source of the leak.

notice, that there is however a slow raising trend of persistent bytes, but that might come from glutin, or glium itself.

As this journey seemed very long wanted to share my findings and ask if you were ok with merging this pr for now to kind of fix or at least make https://github.com/tomaka/winit/issues/158 better?

My plan then was to continue with understanding what is leaking still in glium, glutin and winit for the fullscreen example and then probably merging the mac os sharing contexts to glutin and then finally the upgrading glutin to 0.10 in glium.

Thanks! and what do you think?

### CODE REVIEW

**Comment by vberger** [comment]
Can someone familiar with the MacOS code review the code itself?

Independently of that, this could use a rebase and an entry in the changelog file. Also, please don't release a new version in this PR, as there are pending breaking changes, next winit version will be 0.9, and we maybe don't want to release it right now.

**Comment by bogdad** [comment]
Hi Viktor thank you!

I rebased, removed the version bump
and modified winit full screen example to be more obvious for checking the leak (not needing glium and glutin things)

Here is the memory profile without the change:
screen shot 2017-10-28 at 16 05 55

notice the upwards trend in the top left graph after pressing enter few times (making new windows fullscreen/not fullscreen)

here is the example without the change
screen shot 2017-10-28 at 16 05 24

notice the flat profile.

I could remove the change to fullscreen example to make it simpler once we are happy with the patch.

Thanks again!

**Comment by francesca64** [comment]
Is this PR still relevant?

**Comment by bogdad** [comment]
Oh, hi! thank you for reminding me about it, I'll check and try to answer in some time

**Comment by bogdad** [comment]
closing in favor of https://github.com/tomaka/winit/pull/481

**Pull request closed without merging**
