### PR TITLE
x11: Always receive Awakened event in run_forever

### LINKED ISSUE #462: Awakened event doesn't always work
See the comment at the top of this code block:

```rust
//! This demonstrates a situation where the the Awakened event doesn't make it from the proxy to the
//! event loop (at least with the X11 backend). If you remove the `run_forever` call, the Awakened
//! event starts to work again. Maybe waiting for events invalidates the Awakened event.
//! Click the window that appears to call the proxy wakeup() method.

extern crate glutin;

fn main() {
    let window_builder = glutin::WindowBuilder::new()
		.with_title("A window")
		.with_dimensions(800, 600);
	
	let mut events_loop = glutin::EventsLoop::new();
	
	let context_builder = glutin::ContextBuilder::new();
	let _gl_window = glutin::GlWindow::new(window_builder, context_builder, &events_loop).unwrap();
	
	let events_proxy = events_loop.create_proxy();
	
	loop {
		let mut events = vec![];
		
		// Wait for events.
		events_loop.run_forever(|event| {
			println!("event: {:?}", event);
			events.push(event);
			glutin::ControlFlow::Break
		});
		
		// Just poll events without waiting.
		events_loop.poll_events(|event| {
			println!("event: {:?}", event);
			events.push(event);
		});
		
		for event in &events {
			match *event {
				glutin::Event::WindowEvent{event: glutin::WindowEvent::MouseInput{state, ..}, ..} => {
					match state {
						glutin::ElementState::Pressed => {
							println!("wakeup()");
							events_proxy.wakeup().unwrap();
						}
						_ => {}
					}
				}
				_ => {}
			}
		}
	}
}
```

When it works, it should print `wakeup()` then `event: Awakened` to the console when the window is clicked. When it does not, it will only print `wakeup()`.

### PR DESCRIPTION
**Pull request by b-r-u**
Do not reset the pending_wakeup boolean at the start of run_forever so
that each call to EventsLoopProxy::wakeup results in an Awakened event.

Fixes #462

### CODE REVIEW

**Comment by francesca64** [comment]
Looks good to me (pending your confirmation that I understand this feature https://github.com/tomaka/winit/issues/462#issuecomment-385184981).

Also, this needs a CHANGELOG entry.

**Comment by b-r-u** [comment]
Done!
Would you like me to squash the commits?

**Comment by francesca64** [comment]
I'll let you in on a winit secret, which is that "Squash and merge" is the only option enabled for merging PRs. So, you don't have to worry about it.

**Comment by b-r-u** [comment]
Good to know :)

**Pull request merged**
