### PR TITLE
Add missing windows virtual key codes

### PR DESCRIPTION
**Pull request by rukai**
Fixes: https://github.com/tomaka/winit/issues/74

### CODE REVIEW

**Comment by tomaka** [comment]
The problem is that having a behaviour that varies between platforms is probably not something we want.
What do the SDL and GLFW do?

**Comment by rukai** [comment]
SDL maintains its own internal keymaps, on windows it generates this based on virtual key code to char conversion (which windows handles correctly)
https://github.com/spurious/SDL-mirror/blob/1969a981b021d2c7a6a45fed7673f7b811a90125/src/video/windows/SDL_windowskeyboard.c#L138

Based on this I have changed my code to handle VK_OEM_* keys by converting them to char and then matching on the correct char.

**Comment by rukai** [comment]
Wayland handles keyboard layouts the same way X11 does.
However winit currently doesnt have the relevant wayland keys mapped, I can do that in a seperate PR if you want?

**Comment by tomaka** [comment]
> Wayland handles keyboard layouts the same way X11 does.

Ok. Let's merge this then. Thanks.

> However winit currently doesnt have the relevant wayland keys mapped, I can do that in a seperate PR if you want?

Yes, that would be another PR if you want to do it.

**Pull request merged**
