### PR TITLE
Implement virtual key translation for emscripten

### PR DESCRIPTION
**Pull request by cactorium**
Just copy and pasted some old code to implement `key_translate_virt`. There was a weird compiler issue in `key_translate` with an unnecessary `mem::transmute` that was also removed. It compiles at least

### CODE REVIEW

**Comment by cactorium** [comment]
It looks like circleci's having trouble checking out the repository?

**Comment by tomaka** [comment]
I think you're the first person apart from me to submit a PR since I added CI for the asm/wasm targets.

Since I can't really try it myself, would you mind trying to insert this line [above `checkout`](https://github.com/tomaka/winit/blob/52a7b07c79f842170e01f10740b569ea428fd12d/.circleci/config.yml#L10)?

```
apt-get update && apt-get install -y git
```

If it doesn't work, then we'll see later.

**Comment by cactorium** [comment]
I think I got it working! It looked like you needed to use `run: apt-get -qq update && apt-get install -y git` based on this: https://discuss.circleci.com/t/cant-checkout-code/11592/2

It turns out the transmute was necessary, it just happened to not be on my machine, so that's back in the code. I also modified the code slightly to prevent a panic if the emscripten string wasn't valid UTF-8, please lemme know if you think that should be reverted

**Comment by tomaka** [comment]
Thanks!

**Pull request merged**
