### PR TITLE
Version 0.18.1

### PR DESCRIPTION
**Pull request by Osspial**

### CODE REVIEW

**Comment by rukai** [comment]
Looks like there are no breaking changes? Can this be 0.18.1?

**Comment by Osspial** [comment]
This has some minor API additions which makes me lean towards releasing this with a full version increment.

**Comment by francesca64** [comment]
@Osspial are you sure you're not just doing this so `EventLoop` 2.0 will be 0.20? That would be pretty cool, so I wouldn't blame you.

Joking aside, I'm not opposed to this, but I personally would've gone with 0.18.1 just for the downstream convenience. I do think it would be nice to establish guidelines for release versioning; AFAIK the most recent discussion is here: https://github.com/tomaka/winit/pull/468#issuecomment-382607437

Anyway, before releasing, I still want to review #730 and investigate #748. Is this intended to be our last (planned) pre-`EventLoop` 2.0 release?

**Comment by Osspial** [comment]
@francesca64 I... hadn't been thinking about that, but now I'm disappointed that I wasn't!

Anyhow, my modus operandi with `0.x.y` releases has been to treat them as standard semver, bumping the `x` number for releases with any API additions and bumping `y` for releases that only have bugfixes. I can see the rationale for treating `y` as the minor version number though, and wouldn't be opposed to releasing this as `0.18.1`.

I was planning for this to be the last pre-EL2.0 release, yes. If you want to hold off on releasing this until we handle #730 and #748, I'd be fine with it.

**Comment by vberger** [comment]
Regarding version numbers, even if this release is 0.18.1, nothing prevents us from releasing eventloop 2.0 as 0.20 and skipping 0.19 in the process. (With wayland-client I went directly from 0.14 to 0.20 with my last big rewrite to mark the fact that it was fundamentally different.)

On this regard, if there are no breaking change, I think it is better if this is released as 0.18.1, so that `cargo update` works out of the box for anyone depending on `winit = "0.18"`, as that is the way cargo interprets semver for pre-1.0.

**Comment by Xaeroxe** [comment]
As a winit user with a few dependencies that also depend on winit releasing this as a patch version would make me very happy,

**Comment by Xaeroxe** [comment]
I just double checked for semver breakage in this release, and I couldn't find any.

**Comment by Osspial** [comment]
Alright, this has been reformatted as `0.18.1`.

**Comment by Osspial** [comment]
@francesca64 Would you be up for releasing the current slate of changes now, then releasing `0.18.2` once the issues you brought up have been addressed?

**Comment by chrisduerr** [comment]
I have nothing to say here, but I'd be in favor of publishing a new version as quickly as possible since things like high resource usage when moving windows in between monitor's is a pretty serious issues which affects a decent number of users.

Just my 2 cents from the perspective of a winit enduser. Otherwise the solution might be to link against the git version of winit temporarily, but that doesn't really help anyone.

**Comment by Osspial** [comment]
Since there hasn't been any comment from @francesca64 and there's a definite benefit for releasing these changes now, I'm going to go ahead and merge this and leave those other two issues for a future patch release.

**Pull request merged**
