### PR TITLE
[DONT MERGE] Experimental (browser-like) keyboard input

### PR DESCRIPTION
**Pull request by pyfisch**
Hi, I plan to improve servos keyboard input and as servo [will depend on winit](https://github.com/servo/servo/pull/17311) this is the right place to gather all the information servo needs about key presses and character input. I don't expect that this will be merged into winit but it should start a discussion what kind of keyboard input winit wants to provide and if it can fulfill a browsers needs. It will also serve me as a reference what kind of information a backend can provide about keyboard input and use it to implement more UI events (correctly) inside servo.

Supported features:
* X11 only
* `key` information about key meaning
  * character value – not only US ASCII but all Unicode
  * special characters like Shift and Control
  * keyboard modifers
  * detect repeating keys
  * no control characters Control+C is "c" with control modifier and not "\x03"
* `code` physical key position
* dead key support for writing characters like é  or ï
 * composition events carry information about pressed diacritcs and aborted composition sequences
 * limitation: Xlib does not create characters containing multiple diacritics like ^ + ´  + a → ấ (chained dead keys) and some others like u with double acute ű but instead writes ü.

How to write a text editor with this?

This path retains the `ReceivedCharacter` event but also supports text entry using only `KeyboardInput` and `CompositionEvent`.  Take all keydown with a character value and add the character value at the cursor position. Special characters like Backspace or ArrowLeft either modify the cursor position or change the text. If a keydown is composing ignore it for entering text but wait for a compositionend event and add its character value at the input position.

How to write keyboard shortcuts?
A shortcut like Control+C can be detected by matching keydown events with the character C and a Control modifier just as with the current system.

For more information see the [UI Events](https://w3c.github.io/uievents/) spec.

cc @jdm What do you think about the events. I think they would allow it to implement the key* and composition* and (before)input events in servo correctly unlike the current glutin backend that only provides a small part of required information.

### CODE REVIEW

**Comment by Ralith** [comment]
Some initial concerns:

- Why is it winit's job to assign special meaning to dead keys? XCompose and XIM in general are already supported. winit should not be implementing its own special snowflake input method.
- This change throws away unrecognized keycodes. We should never discard information like that. A game should not need to have hardcoded knowledge of the label printed on a keycap for the user to be able to bind it, no matter what a W3C spec says--especially with so small a hardcoded set.
- AFAIK `XFilterEvent` should be called on all events, not just key events. This was previously correct, so this is a regression.
- Some helper methods modify the X event in-place when that is not their express purpose. This is a maintenance hazard, as it may not be clear to future contributors when and why mutations are being made. A simple reordering of method calls would produce incorrect results, for example.
- Relying on another crate for public event types is a stability risk and limits our flexibility. Is that justified? Most of winit's users are not implementing that W3C spec.

**Comment by jwilm** [comment]
>  A game should not need to have hardcoded knowledge of the label printed on a keycap for the user to be able to bind it

AFAICT, this isn't actually possible with current master. Say for a moment the user has a keyboard layout that has `d` in place of `c`. Winit will emit virtual key codes of `c` still because the keymap has not yet been applied. This is fine without modifiers, because the received character will actually be 'd'. When there is modifiers, the received character changes, and there's no way to recover what the actual key was.

**Comment by Ralith** [comment]
> AFAICT, this isn't actually possible with current master

winit currently accurately reports `ScanCode`s for *all* key events. These are stable and layout-insensitive, and hence the correct datum on which to build a generic keybinding system. This PR would defeat that.

> Say for a moment the user has a keyboard layout that has d in place of c. Winit will emit virtual key codes of c still because the keymap has not yet been applied. This is fine without modifiers, because the received character will actually be 'd'. When there is modifiers, the received character changes, and there's no way to recover what the actual key was.

It sounds like there's some confusion between "the received character" and `VirtualKeyCode` here. In current winit's X11 backend, `VirtualKeyCode` is determined according to the X11 keysym, which *is* layout-sensitive but is *not* the same thing as the actual text input. Unfortunately, this is not terribly consistent across backends, although it's a bit of a dubious notion to begin with.

**Comment by tomaka** [comment]
> Say for a moment the user has a keyboard layout that has d in place of c. Winit will emit virtual key codes of c still because the keymap has not yet been applied.

In theory the virtual key code produced by winit will be `D` in this case.

**Comment by jwilm** [comment]
@tomaka 

That would be great, but it doesn't seem to be true.

https://github.com/jwilm/alacritty/issues/682
https://github.com/jwilm/alacritty/issues/93#issuecomment-306788447

I've also experienced this myself on macOS. It may only be an issue on that platform.

**Comment by jwilm** [comment]
GLFW has a function [glfwGetKeyName] which serves the purpose of applying the keyboard layout/locale to solve this issue. It returns a string with a value like `"d"` in the case I described above. This sounds somewhat similar to part of @pyfisch's proposal.

[glfwGetKeyName]: http://www.glfw.org/docs/latest/group__input.html#ga237a182e5ec0b21ce64543f3b5e7e2be

**Comment by vberger** [comment]
> That would be great, but it doesn't seem to be true.

Well, that's interesting, because winit correctly sees that my keyboard is AZERTY (and not QWERTY) and raises the correct VirtualKeyCode according to my keyboard under X11..

**Comment by jwilm** [comment]
Confirmed still an issue on macOS using latest winit:

```
WindowEvent { window_id: WindowId(Id(140297008959056)), event: Focused(true) }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: ReceivedCharacter('a') }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 1, state: Pressed, virtual_keycode: Some(S), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: ReceivedCharacter('r') }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 2, state: Pressed, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: ReceivedCharacter('s') }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 1, state: Released, virtual_keycode: Some(S), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Pressed, virtual_keycode: Some(F), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: ReceivedCharacter('t') }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 2, state: Released, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Released, virtual_keycode: Some(F), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140297008959056)), event: Focused(false) }
```

Using Colemak from system settings, typing "arst" triggers appropriate received chars but emit ASDF for virtual key codes. Normally I use a WASD keyboard which can switch the layout at hardware level which effectively works around this issue.

**Comment by vberger** [comment]
So this is a MacOS issue?

The code translating raw keycodes to virtual keycodes is platform-dependant (it's not even the same between x11 and wayland). So if this is a bug with the macos backend an issue should be openend for it, I guess.

**Comment by pyfisch** [comment]
Thanks for all your comments!

> * Why is it winit's job to assign special meaning to dead keys? XCompose and XIM in general are already supported. winit should not be implementing its own special snowflake input method.
It really should not be winits job but with the current setup of using XKeyPress/XKeyRelease Xlib just did not provide a better method to get this information. Dead keys are somewhat *special* and I tried to follow the established standard from the web to handle them. I would appreciate it very much if you could point me to documentation about XCompose and XIM and how to handle dead keys with them or even help implementing it. The comments scattered between the lines already hinted that XInput2 and xkbcommon should be used but I did not know how to use them (mainly due to missing docs).

> * This change throws away unrecognized keycodes. We should never discard information like that. A game should not need to have hardcoded knowledge of the label printed on a keycap for the user to be able to bind it, no matter what a W3C spec says--especially with so small a hardcoded set.
Adding this information back will be easy but just like current keycodes they will remain platform dependent. Actually a game can use the key code representing the physical position of the key in most cases. If the keyboard in not entirely different from the usual form the key will be recognized and labeled independently from the label printed on the keycap. 

> * AFAIK XFilterEvent should be called on all events, not just key events. This was previously correct, so this is a regression.
Do you have more information on this? The comment mentioned handling dead keys and "input method funtimes" but these are handled manually. I could not observe any other events changed by XFilterEvents.

> * Some helper methods modify the X event in-place when that is not their express purpose. This is a maintenance hazard, as it may not be clear to future contributors when and why mutations are being made. A simple reordering of method calls would produce incorrect results, for example.
Yes the keyboard handling should be rewritten using some library like xkbcommon or use more modern X11 functions. I hope it will become more robust in this case.
> * Relying on another crate for public event types is a stability risk and limits our flexibility. Is that justified? Most of winit's users are not implementing that W3C spec.
I can't really answer this. But I believe providing good support for international keyboards and keycodes independent from platform and keyboard layout is beneficial to many of winit's users. The reason for these types to be in a separate crate is that servo should use these types too but servo does not want to depend on winit at all times so a common dependency solves this issue.

Regarding the scancode/actual text input issue:
* Most platforms provide a scancode representing the physical key location. These numeric codes are platform dependent. The Web API maps them to "codes" inspired by the US-Keyboard offering a cross-platform way to address physical keys. A game can use WASD keys without knowing the label printed on them. It should be very rare that there are keys without a corresponding Web code.
* My approach is somewhat similiar to `glfwGetKeyName` but it takes more information into account for getting a character value like shift level other keyboard state. It also returns non-latin keys if they are part of the keyboard layout.

**Comment by Ralith** [comment]
> I would appreciate it very much if you could point me to documentation about XCompose and XIM and how to handle dead keys with them or even help implementing it.

Again, XIM support, which implies XCompose support, was already implemented; your changes partly break it and implement redundant behavior.

> Adding this information back will be easy but just like current keycodes they will remain platform dependent.

That is the intended behavior. Their purpose is to allow you to correlate presses of the same key on a given system, nothing more.

> Actually a game can use the key code representing the physical position of the key in most cases.

Winit currently handles keycodes correctly in *all* cases; "most" is ill-defined, but certainly a regression.

> Do you have more information on this? The comment mentioned handling dead keys and "input method funtimes" but these are handled manually. I could not observe any other events changed by XFilterEvents.

Input method logic, including but not limited to dead keys, is provided by the platform; it is not appropriate to handle them manually, and will break things. Your system configuration may only care about key/press release, but that is nonetheless not a correct use. Refer to [the documentation](ftp://www.x.org/pub/current/doc/man/man3/XFilterEvent.3.xhtml); note in particular the absence of any restrictions on events of interest.

If you're having difficulty with dead keys on your system, then either your system is misconfigured or there is an error in winit's use of XIM. The solution is not to hardcode a tiny fragment of your desired XIM configuration inside winit.

> Yes the keyboard handling should be rewritten using some library like xkbcommon or use more modern X11 functions. I hope it will become more robust in this case.

This doesn't seem to be a response to my comment. The helper methods you wrote introduce unnecessary fragility regardless of how keyboard handling is ultimately accomplished.

> But I believe providing good support for international keyboards and keycodes independent from platform and keyboard layout is beneficial to many of winit's users.

In its current state, this PR represents a regression in support for international text input due to the input method confusion. Keycodes are inherently platform dependent. I agree that having slightly abstracted keycodes that are often at a predictable location is useful, but support for other cases should not and does not need to be sacrificed to accomplish that.

> The reason for these types to be in a separate crate is that servo should use these types too but servo does not want to depend on winit at all times so a common dependency solves this issue.

Servo is perfectly capable of mapping winit events into web-style events in its own code to whatever extent it feels is necessary. I'm not categorically opposed to having a more reusable event type if it can be made non-lossy, but I'd want input from other winit maintainers regarding stability concerns first. I will not approve changes that throw away useful previously-available information.

> My approach is somewhat similiar to glfwGetKeyName but it takes more information into account for getting a character value like shift level other keyboard state. It also returns non-latin keys if they are part of the keyboard layout.

Keyboard state beyond the keymap is not relevant to the name of a key.

**Comment by pyfisch** [comment]
I have pushed a commit that brings platform keycodes back.

@Ralith 

> Winit currently handles keycodes correctly in all cases
What is the exact behavior you expect here? For which keypreses/releases is an event with keycode created?

I cannot stress enough that this is a prototype implementation. The real one will use functionality of Xinput2/Xim/Xkbcommon instead of my helper methods. This will make the implementation more robust and correct logic flaws present in the prototype.

Are there any problems you see with the current event model?

**Comment by Ralith** [comment]
The existing behavior in winit is correct: All X key events that are not consumed by the X input method yield a winit key event, including an accurate keycode.

The change is an improvement, but I'm concerned that it would be confusing for users to have two different "code" values which are almost but not quite the same. I'm not a fan of making the winit API less ergonomic for the sake of using an external type. Maybe the keyboard-types package could be talked into a more versatile `Code` enum?

**Comment by pyfisch** [comment]
> Maybe the keyboard-types package could be talked into a more versatile Code enum?

Probably. I just don't know how the new code enum would look like. Platform dependent scancodes and portable named codes do not have a 1 to 1 one mapping. The scancode is different for every platform and it may not have a corresponding portable code, there may be even multiple scancodes mapping to the same portable codes in rare cases.

**Comment by Ralith** [comment]
> I just don't know how the new code enum would look like. Platform dependent scancodes and portable named codes do not have a 1 to 1 one mapping.

I was imagining an `Unidentified(u32)` case.

> there may be even multiple scancodes mapping to the same portable codes in rare cases.

If there are in fact cases like that, then this sounds like a dubious approach overall. I don't want to give the appearance of encouraging users to use a lossy encoding of important data like "which key actually got pressed."

**Comment by pyfisch** [comment]
> I was imagining an Unidentified(u32) case.
Not sure that this is a good idea because adding new codes becomes a breaking change since software recognizing a specific Unidentified(u32) code would now see a different code.

> If there are in fact cases like that, then this sounds like a dubious approach overall. I don't want to give the appearance of encouraging users to use a lossy encoding of important data like "which key actually got pressed."
I did not find such a case in the wild. As long as the keycodes are different only one key will be mapped to any given code.

**Comment by Ralith** [comment]
> Not sure that this is a good idea because adding new codes becomes a breaking change since software recognizing a specific Unidentified(u32) code would now see a different code.

Adding new cases to an enum is already a breaking change.

**Comment by pyfisch** [comment]
> Adding new cases to an enum is already a breaking change.

Not if we prevent exhaustive matching. One can always add a hidden enum variant and there is even a "non_exhaustive" tracking issue.

**Comment by pyfisch** [comment]
While servo still needs better keyboard input I no longer think it is a good idea to add browser-like keyboard handling to winit at this time.

**Pull request closed without merging**
