### PR TITLE
Implement android events and wake event loop

### PR DESCRIPTION
**Pull request by MortimerGoro**
Implement android events and wake event loop.

### CODE REVIEW

**Comment by tomaka** [comment]
The PR looks good, but for your information the `WindowProxy` is no longer supported.
The whole android backend is waiting to be reworked for the new API.

**Comment by tomaka** [comment]
Also `Event::Awakened` will eventually be removed, so I'd prefer if you don't start using it now.

**Comment by MortimerGoro** [comment]
@tomaka Ok. So you want an updated PR with the Event::Awakened removed? This PR comes from the Servo fork which still uses WindowProxy (hope that we can merge the fork in the future)

**Comment by tomaka** [comment]
> So you want an updated PR with the Event::Awakened removed?

Yes. Since there's no android continuous integration, there is a risk that android compilation breaks when we remove Event::Awakened from the API.

> This PR comes from the Servo fork which still uses WindowProxy (hope that we can merge the fork in the future)

The servo fork of glutin doesn't use winit yet as far as I know.

**Comment by MortimerGoro** [comment]
> Yes. Since there's no android continuous integration, there is a risk that android compilation breaks when we remove Event::Awakened from the API.

Done. Removed it from the Glutin PR too.

> The servo fork of glutin doesn't use winit yet as far as I know.

Not yet

**Pull request merged**
