### PR TITLE
Implement window transparency on macOS.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/tomaka/winit/issues/57.

### CODE REVIEW

**Comment by frewsxcv** [comment]
r? @mitchmindtree 

`cargo run --example transparent`

**Comment by mitchmindtree** [comment]
Looks good to me on OS X 10.10.5 :+1:

screen shot 2016-11-27 at 11 19 52 am

**Comment by tomaka** [comment]
I'm hesitant to merge this because of the weird travis failure.

**Comment by frewsxcv** [comment]
@tomaka Currently, all the changes in this PR are commented out and the fail still exists, FWIW.

**Comment by frewsxcv** [comment]
I think that issue should be fixed by https://github.com/rust-lang/cargo/issues/3333.

**Comment by tomaka** [comment]
You should probably remove your `tmp` commits.

**Comment by frewsxcv** [comment]
`tmp` commits are removed, but fetching from crates.io is broken on the nightlies. So might have to wait another day or two.

**Comment by frewsxcv** [comment]
@tomaka nightly is building now.

**Pull request merged**
