### PR TITLE
Update windows set_cursor to use more variants of MouseCursor

### PR DESCRIPTION
**Pull request by Osspial**
Specifically, this PR:

* Maps diagonal sizing cursors
* Maps `Grab`, `Grabbing`, `Move`, and `AllScroll` to the all-directional sizing cursor
* Remaps `Progress` from plain waiting circle to circle with pointer.

### CODE REVIEW

**Comment by Kurble** [comment]
Nice! This is is exactly what I need.

**Comment by francesca64** [comment]
This should probably have a CHANGELOG entry.

**Comment by francesca64** [comment]
You seem to have inadvertently introduced an unrelated commit.

**Comment by Osspial** [comment]
Whoops, it seems like I had! That should be gone now.

**Comment by francesca64** [comment]
Thanks! Sorry that this took 2 months.

**Pull request merged**
