### PR TITLE
Wayland backend rewrite

### PR DESCRIPTION
**Pull request by vberger**
This is a rewrite of the wayland backend using the new wayland-client API.

~~Breaking-changes:~~

- ~~the signature of the methods `get_wayland_surface` and `get_wayland_display` of the trait `os::unix::WindowExt` changed to return a reference to a rust object rather than a raw pointer. This will allow better type-safe integration with drawing libraries. The raw pointer can still be accessed using the `ptr()` method on these objects, provided by the `Proxy` trait from wayland-client.~~

~~If this breaking-change is not desirable, we can work around it by creating two new methods and keeping (but deprecating) the old ones.~~ The internals are exposed as two secondary unstable methods.

Stuff that worked before but is not yet re-implemented:

- ~~Scroll events (the wayland protocol for these evolved and I need some time to figure out the proper handling)~~

Stuff that didn't work before and does still not work (not working functions are no-op-ed)

- Touch events
- D&D events
- Moved events / `get_position` / `set_position` (will likely never be possible on wayland)
- `Awakened` / `Refresh` events
- `show` / `hide`
- `set_cursor`
- `set_cursor_state` (not yet possible on wayland, but might be in a soon-ish future)
- `hidpi_factor`
- `set_cursor_position` (not possible on wayland, I don't know if it will)

### CODE REVIEW

**Comment by vberger** [comment]
Okay, with these last commits I've reached the same feature set as the current backend, meaning that merging this PR should not introduce any regressions. :smile:

**Comment by tomaka** [comment]
@ozkriff @Vinatorul Can I merge this?

Both this PR and the glutin rework will need to land eventually, it's just a matter of deciding in which order.

My suggestion is to merge this one now, and in the meanwhile for the glutin rework you use a precise commit in the dependency for winit (eg. `winit = { git = "https://github.com/tomaka/winit", tag="fdf8a21" }`).

**Comment by ozkriff** [comment]
@tomaka Of course! We haven't managed to make it work anyway)

I'll try to rebase my branch. But if it will be difficult then we'll take "precise commit" route :)

**Comment by vberger** [comment]
@ozkriff This rewrite should not change anything for glutin except expose a new method on `winit::os::unix::WindowExt` : `get_wayland_client_surface` that you should be able to use in conjuction of the `egl` odule of `wayland-client-7.0` to get an EGL surface, see https://docs.rs/wayland-client/0.7.4/wayland_client/egl/struct.WlEglSurface.html

**Comment by ozkriff** [comment]
@vberger awesome! :)

**Pull request merged**
