### PR TITLE
x11: Support numpad arrows/Home/End/PageUp/PageDown/Insert/Delete

### PR DESCRIPTION
**Pull request by forbjok**
Uncommented and corrected x11 key mappings for the numpad keys with num-lock turned off.

### CODE REVIEW

**Comment by tomaka** [comment]
Seems suspicious that this was commented out, but I don't remember why it was the case.

**Comment by forbjok** [comment]
There are a lot of commented-out x11 keycodes in there. My guess is they were copied from a list at some point, and only the ones deemed of immediate importance were mapped correctly, while the rest were just left commented-out to be fixed later.

That said, after posting this, I found another pull request that among other things maps some of these, but to other keycodes.
https://github.com/tomaka/winit/pull/114

There is some discussion there about whether the numpad keys should map to the same VirtualKeyCode regardless of numlock state. While for my particular case (the terminal alacritty using it for input) this does not matter, I can see this being useful for other purposes, such as games where you might want to use the numpad keys as an additional input separate from the regular arrow keys. In that case, I guess alacritty would have to be changed to use a different method of mapping them to input depending on numlock state.
It really depends on what the intended purpose of VirtualKeyCodes is - to be able to uniquely identify each physical key on the keyboard, or to identify their functions.

However, either way, they should be mapped to something so that it's possible to use them.

**Comment by francesca64** [comment]
I'm still of the belief that the `VirtualKeyCode`s should be dependent on numlock state, as numlock changes the semantic meaning of those keys. Someone wishing to use them as directional/etc. input in a game would use scancodes, which refer to physical key positions.

**Comment by forbjok** [comment]
Yeah, I think I agree on that.

**Comment by francesca64** [comment]
What's stopping this from being merged? It seems we have a good consensus.

**Comment by forbjok** [comment]
I changed it to use XK_KP_Page_Up and XK_KP_Page_Down instead of Prior and Next, as they have the same underlying code and are better named, and added a changelog entry for the change.

**Comment by tomaka** [comment]
Thanks!

**Pull request merged**
