### PR TITLE
Set #[repr] of VirtualKeyCode to u32

### LINKED ISSUE #87: Add repr(u8) for VirtualKeyCode
Enabling repr(u8) would mean that an array could be used for handling keys via i.e ecs instead of a hashmap. See amethyst/amethyst#114

### PR DESCRIPTION
**Pull request by torkleyy**
This allows to have an array of `bools` for the key states.

Fixes #87

### CODE REVIEW

**Comment by Ralith** [comment]
There are far more than 2^8 distinct semantic keyboard keys in the world. #164 had to extend `ScanCode` to `u32`; picking `u8` for `VirtualKeyCode` would be very strange and is more or less guaranteed to require fixing later.

**Comment by torkleyy** [comment]
@Ralith So better a `#[repr(u32)]`?

**Comment by Ralith** [comment]
That should be very future-proof, yeah.

**Comment by torkleyy** [comment]
Changed and rebased

**Pull request merged**
