### PR TITLE
macOS: Implement NSTextInputClient

### PR DESCRIPTION
**Pull request by francesca64**
Issues this hopefully fixes:
- #263
- jwilm/alacritty#61
- jwilm/alacritty#209
- jwilm/alacritty#372
- jwilm/alacritty#748 ✔️
- jwilm/alacritty#764 ✔️
- jwilm/alacritty#935 ✔️
- jwilm/alacritty#1040 ✔️
- jwilm/alacritty#1041 ✔️
- ~~jwilm/alacritty#1064~~ ❌

(I'm not sure about all of these. Hopefully we can get feedback on most of them.)

Alacritty branch for easy testing: https://github.com/francesca64/alacritty/tree/macos-kb

@kwonoj are you interested in trying this out?

### CODE REVIEW

**Comment by francesca64** [comment]
Note that this isn't perfect: https://github.com/tomaka/winit/issues/263#issuecomment-388913791
> There's still future work that needs to be done, i.e. it's not currently possible to display a cute little underlined `´` prior to `é` appearing. This is far more bothersome when working with IME, but it's still a big improvement over the current state of affairs.

**Comment by kwonoj** [comment]
Cool thing, I was recently realized this is needed and chanhes arrived even before I dig into impl :)

I'll try some quick testing around tomorrow once I get to access to my mac machine.

**Comment by kwonoj** [comment]
Also (somewhat) related : https://github.com/servo/servo/issues/20770

**Comment by kwonoj** [comment]
I just gave it a try and it doesn't look like working as expected - I tried simple KR char composition to `한글 `(added _space_ to trigger composition end) , and belows are event I could observe:

```
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 79, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(M), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: ReceivedCharacter('ㅎ') }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 46, state: Released, virtual_keycode: Some(M), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Pressed, virtual_keycode: Some(F), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Released, virtual_keycode: Some(F), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 1, state: Pressed, virtual_keycode: Some(S), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 1, state: Released, virtual_keycode: Some(S), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 40, state: Pressed, virtual_keycode: Some(K), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: ReceivedCharacter('ㅏ') }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 40, state: Released, virtual_keycode: Some(K), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 5, state: Pressed, virtual_keycode: Some(G), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 13, state: Pressed, virtual_keycode: Some(W), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 5, state: Released, virtual_keycode: Some(G), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 13, state: Released, virtual_keycode: Some(W), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 49, state: Pressed, virtual_keycode: Some(Space), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: ReceivedCharacter('글') }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: ReceivedCharacter(' ') }
WindowEvent { window_id: WindowId(Id(140512591906368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 49, state: Released, virtual_keycode: Some(Space), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

Particular odd point is `ReceivedCharacter`, in order it emits
1. `ㅎ`
2. `ㅏ`
3. `글`

and it doesn't have specific rules, 1 emits when composition starts, but 2 is neither composition starts nor composition end (cause last consonant `ᆫ` for char `한` supposed to be char right before composition end), then for next char it doesn't emit any vowel / consonant but emits composited char once composition completes via pressing _space_ key.

**Comment by francesca64** [comment]
I tried with 390 Sebulshik, and I seem to be able to produce the desired sequence in Alacritty, just like in Terminal.app. `ReceivedCharacter` contains code points, not graphemes, so maybe that's why the events aren't what you expect?

**Comment by kwonoj** [comment]
But still in those cases, what's recommended way to process keyevt with compositions? In this case receivedcharacter is pretty much unusable, so applications have to filter it away and compose via keyboardinput only. 

For cases like broswers implements composition* event, it surpresses keydown while composition's in progress so it is acceptable (filter out receivedchar) but

1. It is hard to figure out when composition is in progress with current keyinputevt (maybe this is up to application level to figure out)

2. Even if receivedchar supposed to display codepoint, current behavior does not emit all codepoints - each kr vowel/consonant have visibile codepoint, so hard to explain why some are received and some are not.

**Comment by francesca64** [comment]
There's not currently a recommendation, and there's plenty of API design that needs to be done. I'm open to suggestions (and detailed explanations of requirements), but it's not something I can put much time into at present.

**Comment by kwonoj** [comment]
I see. I'll try to check few other things than receivedcharacter event as well.

**Comment by kwonoj** [comment]
So for non-emitting `ReceivedCharaters`, it seems `insert_text()`(https://github.com/tomaka/winit/pull/518/files#diff-58d7f5aca673e64eda4815ae176040b2R236)  itself is not even being called for certain composition status. I can't figure out exactly when it's not being called / why, probably worth to file separate issue instead of trying to dig out in this PR maybe?

**Comment by francesca64** [comment]
Yeah, I'd like to get this merged and worry about further improvements afterwards.

**Comment by k0nserv** [comment]
Dead keys are not working for me at all with this version, also Japanese input also does not work. I could however switch keyboard while Alacritty was focused. I'm on Sierra(10.12.6)

**Comment by petobens** [comment]
Hi @francesca64 thanks for this awesome fix (now I can finally input tildes in spanish characters :) ). Two things I did notice when using your alacritty branch on Mac and U.S keyboard layout are: i) before I use to be able to hold the `j` key in vim and the cursor would go down lines as long as I don't release such key. Now in order to achieve such behaviour I need to hold and release j (i.e holding it down only works to go one line down but not further than that); and ii) for some reason now my <Enter> doesn't seem to work (whereas if I press <Ctrl-Enter> then I can actually mimic/send an <Enter> keystroke). Is that expected?

Once again thanks for such an amazing work. Btw Will there be a PR to alacritty with these changes?

**Comment by petobens** [comment]
I'm always on alacritty (not using terminal.app). The Enter issue happens only on tmux (and not on vanilla /plain alacritty). The j (or k) issue happens in both cases and inside vim or outside (for instance using less). It might have something to do with my own setup if you cannot reproduce it. Thanks!

**Comment by francesca64** [comment]
I'll be sure to investigate that before releasing anything. I'm guessing the i/j thing happens with any key?

**Comment by petobens** [comment]
>  I'm guessing the i/j thing happens with any key?

Indeed.

> I'll be sure to investigate that before releasing anything.

Thank you!

**Comment by francesca64** [comment]
@petobens `cargo update` and let me know if it's fixed. (If it doesn't work, double check that it pulled in https://github.com/francesca64/winit?branch=macos-kb-regressions#a9860a92)

**Comment by k0nserv** [comment]
I was using Swedish Pro and trying to type e.g ´ procudes the following.

```
glutin event: WindowEvent { window_id: WindowId(Id(0)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 24, state: Pressed, virtual_keycode: Some(Equals), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(0)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 24, state: Released, virtual_keycode: Some(Equals), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

The hardware keyboard in this case is a UK apple magic, worth nothing that equals is what is printed on the key used and what you get when using a UK layout.

**Comment by francesca64** [comment]
@k0nserv that's not a regression, is it? If it's not a regression, then report an issue for it. I'm quite exhausted, so at the moment I'm only addressing things that block a release.

**Comment by k0nserv** [comment]
Nope it’s not a regression, but I guess it might be an edge case? Anyway thanks for the great work 👍

**Comment by petobens** [comment]
@francesca64 both fixes work :) Thank you!!

**Pull request merged**
