### PR TITLE
compile with icon_loading feature on docs.rs

### PR DESCRIPTION
**Pull request by tinaun**
these functions should be more visible now.

### CODE REVIEW

**Comment by francesca64** [comment]
Thanks! I didn't know about that option.

Do you think the documentation makes it clear enough that those methods are behind a feature?

...I've also noticed that I accidentally made `Icon::to_cardinals` public, which is baaaad.

**Comment by tinaun** [comment]
i thought about listing the methods that icon_loading enables in the struct level docs, but theres no real preferred way of doing this i can find

**Comment by francesca64** [comment]
Yeah, I couldn't find any "official" recommendation, but I like to err on the side of safety.

I hope you don't mind that I made the change myself, but I'd feel like I were being annoying if I told you what sentence I wanted verbatim.

**Comment by tinaun** [comment]
less work for me :v

**Pull request merged**
