### PR TITLE
Re-organize platform/linux to prepare for API transition

### PR DESCRIPTION
**Pull request by vberger**
This is built on top of #148 (and thus should be merge after).

This PR re-organises `src/api/` to put it inside `src/platform/linux`, and moves the api transition boilerplate into the `x11` and `wayland` modules.

This is the groundwork for transitioning these two backends to the new EventsLoop API.

### CODE REVIEW

**Comment by vberger** [comment]
I did not use the api generation macro, but rather expanded it by hand for both modules. This was necessary because the actual implementation of the boilerplate is not exactly the same as the one generated by the macro, due to the nesting in `platform/linux`.

**Comment by tomaka** [comment]
Looks good.

**Comment by tomaka** [comment]
> (and thus should be merge after)

Well, that triggered merge conflicts.

**Comment by vberger** [comment]
Ah, I'll rebase it.

**Pull request merged**
