### PR TITLE
Update x11-dl

### LINKED ISSUE #376: Crash in Xlib_xcb in release
Repro case on Linux:
```bash
git clone https://github.com/gfx-rs/gfx -b pre-ll
cd gfx
cargo run --release --example terrain
```

### PR DESCRIPTION
**Pull request by GabrielMajeri**
Fixes #376.

### CODE REVIEW

**Comment by tomaka** [comment]
This PR is unfortunately not very useful because a user can also apply the fix by running `cargo update`.
If we merge this PR and bump winit, then the user will have to run `cargo update` as well anyway.

**Comment by GabrielMajeri** [comment]
@tomaka I understand, should we add a warning to the README or something? Or is there any way to force Cargo to update a dependency? If we yank the old version, will it display a warning message?

**Comment by tomaka** [comment]
I suppose one solution would be to yank the old version of x11-dl.

**Comment by vberger** [comment]
Still, we can merge this PR (without necessarily bumping winit version now). This will ensure any new dependency on winit will accidentally pull a bad version of x11-dl. No?

**Pull request merged**
