### PR TITLE
Use smithay-client-toolkit's dpi handling.

### PR DESCRIPTION
**Pull request by dvc94ch**
This depends on https://github.com/smithay/client-toolkit/pull/46

### CODE REVIEW

**Comment by dvc94ch** [comment]
ping @vberger

**Comment by dvc94ch** [comment]
Done

**Comment by francesca64** [comment]
@vberger should this have a CHANGELOG entry?

**Comment by dvc94ch** [comment]
> should this have a CHANGELOG entry?

It doesn't really change anything from a winit user perspective, it works identically to the current version but is IMO easier to read. The only gain for winit is dpi issues affect all smitahy-client-toolkit users and should be opened or moved to the smithay-client-toolkit repo, so less code to maintain, and for smithay-client-toolkit users the advantage is they have tried and tested dpi handling.

**Pull request merged**
