### PR TITLE
625 macos modifiers

### LINKED ISSUE #623: On macOS, releasing a key while holding command does not send event
When I press and released a key, while holding the command key, on macOS (10.13.3) - I get the pressed event, but no corresponding released event. When not holding the command key (even if other modifier keys are held) the released event appears to fire correctly.

Steps to reproduce:

1. Run `cargo run --example window`
2. Hold the command key
3. Press and release the H (or any other) key twice

Expected result:

There should be two released events printed to the console, in between the pressed events.

Actual result:

No release events are sent:
```
WindowEvent { window_id: WindowId(Id(140272942043600)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 4, state: Pressed, virtual_keycode: Some(H), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
WindowEvent { window_id: WindowId(Id(140272942043600)), event: ReceivedCharacter('h') }
WindowEvent { window_id: WindowId(Id(140272942043600)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 4, state: Pressed, virtual_keycode: Some(H), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
WindowEvent { window_id: WindowId(Id(140272942043600)), event: ReceivedCharacter('h') }
```

I `git bisect`ed and got dec728cfa28547f17c650dd945d5d2b73086f879 as the first commit with the issue - hopefully that helps.

### LINKED ISSUE #625: macos: modified key issues
Not totally sure these are all related, but:

https://github.com/jwilm/alacritty/issues/1336
https://github.com/jwilm/alacritty/issues/1358
https://github.com/jwilm/alacritty/issues/1428
https://github.com/tomaka/winit/issues/623

I suspect these all started with https://github.com/tomaka/winit/pull/518

@francesca64 has given some direction [here](https://github.com/jwilm/alacritty/issues/1428#issuecomment-404956134)

### PR DESCRIPTION
**Pull request by sodiumjoe**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created an example program if it would help users understand this functionality

fixes #625
fixes #623

### CODE REVIEW

**Comment by sodiumjoe** [comment]
just tested with [this branch](https://github.com/jwilm/alacritty/pull/1403) of alacritty and it appears to work great

**Comment by francesca64** [comment]
Thanks! This looks great.

**Comment by sodiumjoe** [comment]
@francesca64 any chance of shipping another patch so we can get this downstream into https://github.com/jwilm/alacritty/pull/1403 😅

**Comment by sodiumjoe** [comment]
@francesca64 https://github.com/tomaka/winit/pull/630

**Pull request merged**
