### PR TITLE
Update cocoa and core-graphics

### PR DESCRIPTION
**Pull request by paulrouget**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created an example program if it would help users understand this functionality

### CODE REVIEW

**Comment by paulrouget** [comment]
I can change the version to 0.17.

**Comment by paulrouget** [comment]
(i've updated the version number)

**Comment by francesca64** [comment]
Thanks for the PR. I'll merge this after the other open PRs.

**Comment by paulrouget** [comment]
Fixed the conflicts.

**Comment by paulrouget** [comment]
Fixed the conflicts.

**Comment by paulrouget** [comment]
@francesca64 is the travis failure expected or did my PR introduced it?

**Comment by paulrouget** [comment]
Just saw https://github.com/erlepereira/x11-rs/issues/88

@francesca64 can we land or do we need to fix this issue first?

**Comment by francesca64** [comment]
I've been merging PRs with this build failure all week, sadly. That said, I'm waiting for the fix for #607 before making a new release.

**Comment by felixrabe** [comment]
#618

**Comment by francesca64** [comment]
Yep! Sorry you had to wait so long.

**Comment by felixrabe** [comment]
Thank you for your hard work here @francesca64. Very much appreciated!

**Comment by Eijebong** [comment]
No problem.😃 Thanks a lot

**Pull request merged**
