### PR TITLE
Add `Window::monitor_id` API

### LINKED ISSUE #197: Add a `Window::get_monitor_id` method to get the monitor under the `Window`
It seems that `NSWindow` has a method for this: https://developer.apple.com/documentation/appkit/nswindow. It also has a method for getting the "deepest" screen in the case that a window is split over multiple screens, though I'm not quite sure what this means.

I'm not yet sure if the other backends provide functionality for getting this info.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This is a follow up to and closes #197.

I've also added a **monitors.rs** example which lists all available monitors and then prints out the name of each monitor as you move the window across them.

Currently the X11 implementation does not work and just returns the same `MonitorId` regardless of moving the window to a different monitor... any ideas @jwilm @Ralith?

@vberger I tried implementing `wl_surface::Handler` like you mentioned in #197, however neither `enter` or `leave` ever seem to get called. I feel like maybe I'm missing something?

I was unable to test the windows backend with multiple monitors (I was testing in a VirtualBox) however it seems to work nicely for a single monitor. If someone could test with multiple monitors that would be great.

I tested the macos implementation and it seems to work nicely.

### CODE REVIEW

**Comment by Ralith** [comment]
> Currently the X11 implementation does not work and just returns the same MonitorId regardless of moving the window to a different monitor... any ideas @jwilm @Ralith?

My understanding is that the core X11 protocol notion of "Screen", as you're accessing via `XScreenNumberOfScreen`, is de-facto obsolete, at least on the desktop; nearly any configuration will have exactly one. I believe the concept that best maps here is the "CRTC." You'll need to link `libXrandr` and use `XRRGetScreenResources` on the (root?) window, then iterate over `0..ncrtc` of the resulting structure, calling `XRRGetCrtcInfo` and using the resulting structure's `x`, `y`, `width`, and `height` members to determine whether the client window in question overlaps that viewport.

Obviously a window can easily lie on multiple CRTCs, so it may be worth reconsidering the exact API here. It seems natural programmatically to select the CRTC containing the origin, but would a user instead expect to get the one containing the majority of the window?

**Comment by Ralith** [comment]
On further examination it looks like XRandR outputs have at most one CRTC associated, so it may be more user-friendly to work in terms of outputs instead. Use `noutput` and  `XRRGetOutputInfo` to iterate, and inspect the `crtc` member using `XRRGetCrtcInfo` to perform the geometry test. I believe that `crtc` will be 0 if the output is not enabled.

**Comment by vberger** [comment]
> @vberger I tried implementing wl_surface::Handler like you mentioned in #197, however neither enter or leave ever seem to get called. I feel like maybe I'm missing something?

Well that's weird. At first glance your implementation seems correct. Maybe there's an issue with you compositor? Can you give a try while setting the env variable `WAYLAND_DEBUG=1`, to see wether the events are send and the client fails to catch them, or the server just doesn't send them?

**Comment by vberger** [comment]
Is this still relevant ? If so, it needs a reabse.

On the flip side, the recent large refactor of the wayland backend should facilitate the implementation for wayland-side greatly, as the window now already tracks which monitors it is displayed on to handle dpi.

**Comment by mitchmindtree** [comment]
Going to close this as it looks like windows now have `get_current_monitor` methods anyway! It could be useful to add the `monitor.rs` example included in this PR though to make it easier to test the monitor API. Maybe I'll do a PR for adding it in the future (anyone else is welcome to beat me to it in the meantime).

**Pull request closed without merging**
