### PR TITLE
macos platform attributes regression

### PR DESCRIPTION
**Pull request by sodiumjoe**
fixed !decorations case and refactored logic to be a little easier to
read

### CODE REVIEW

**Comment by sodiumjoe** [comment]
I tested this with all the permutations of `.with_decorations` and platform attributes that make sense.

@edwin0cheng can you take a look?

**Comment by edwin0cheng** [comment]
Do we need to handle `pl_attrs.titlebar_transparent = true` here ? Or do i miss something ?

**Comment by sodiumjoe** [comment]
@edwin0cheng nice catch, I missed that the close button was broken. I had accidentally duplicated `NSMinitiaturizableMask` instead of including `NSClosableMask`. This should now be fixed. I've tested with all the combinations.

`titlebar_transparent` is handled later on L704. It's a little weird, because generally you would want to use that with `fullsize_content_view`, but since we offer those separately, I figured it's up to the consumer to use those together.

**Comment by sodiumjoe** [comment]
@edwin0cheng to be clear, I believe it *is* now the case that the final `else` arm of the conditional represents the default case.

**Comment by edwin0cheng** [comment]
>to be clear, I believe it is now the case that the final else arm of the conditional represents the default case.
Maybe we could add a comment to describe that.

**Comment by edwin0cheng** [comment]
Anyway, Look good for me, I tested other weird cases, couldn't find any bugs too.

**Comment by sodiumjoe** [comment]
@edwin0cheng added that comment, thanks for testing!

**Comment by sodiumjoe** [comment]
@francesca64 sorry about the churn on this issue, but I think this is good to merge now.

**Comment by francesca64** [comment]
@edwin0cheng thanks for reviewing this!

@sodiumjoe you have nothing to apologize for. The logic is a lot easier to follow now, so I'm happy.

Thinking more about releases, I've noticed that the changelog is already getting pretty long. I think it would make sense to cut another release around the end of the week.

**Comment by sodiumjoe** [comment]
@francesca64 sounds great, thanks!

**Pull request merged**
