### PR TITLE
Update parking_lot and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by francesca64** [comment]
Any particular reason you want a release?

**Comment by Eijebong** [comment]
Because I was looking at bumping parking_lot in servo and we don't allow duplicates in there but if that's bothering you I can remove the bump and wait.
I'm just used to bumping stuff when I do that kind of things ;)

**Comment by francesca64** [comment]
That's alright. You just have to update the CHANGELOG accordingly, i.e. https://github.com/tomaka/winit/pull/587/files

**Comment by Eijebong** [comment]
Done

**Comment by francesca64** [comment]
Thanks!

**Pull request merged**
