### PR TITLE
XIM support for sending spot to IME

### PR DESCRIPTION
**Pull request by Determinant**
This exposes an API that enables the app to adjust the IME box according to the cursor position.

### CODE REVIEW

**Comment by jwilm** [comment]
LGTM as well. Several other applications with XIM support take a similar approach.

**Comment by tomaka** [comment]
I have absolutely no idea what a "XIM spot" is.

**Comment by Determinant** [comment]
@tomaka https://www.x.org/releases/X11R7.6/doc/libX11/specs/libX11/libX11.html#id2792209
TLDR: "spot" means the location hint sent to the selected input method in X11.

**Comment by tomaka** [comment]
Well, I don't have anything against this change.

**Pull request merged**
