### PR TITLE
version 0.18.0

### PR DESCRIPTION
**Pull request by sodiumjoe**
- ~[ ] Tested on all platforms changed~
- ~[ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~
- ~[ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~
- ~[ ] Created an example program if it would help users understand this functionality~

### CODE REVIEW

**Comment by vberger** [comment]
I've added a note in the changelog precising that F16-F24 was a breaking change. That's unfortunate, I was hoping we could have this release without breaking changes.

While we are at it, I'll check if there are other breaking PRs soon-to-be-merged that we might want to merge before the release.

**Comment by sodiumjoe** [comment]
fixed readme

**Comment by sodiumjoe** [comment]
rebased master

**Comment by francesca64** [comment]
Sorry I've been silent on this! There are two concerns that need to be addressed:
1. #683 broke Rust 1.24.1 compatibility, which will be resolved by PistonDevelopers/image#828.
2. #685 could be considered an upcoming breaking change, since it requires `cocoa` 0.18. We're currently using `cocoa` 0.17, and a type from that is part of our public API [in a very minor way](https://github.com/tomaka/winit/blob/214e157e5df4e3853f4c83269b04b88146d623d8/src/os/macos.rs#L50). I doubt that impl has ever been used by consumers (or was ever intended to be), so it's probably a good idea to just prevent it from being exposed.

**Comment by Osspial** [comment]
Could we also merge #652 for 0.18? I think all issues with that have been resolved.

**Comment by rukai** [comment]
@sodiumjoe can you please set the version of image crate to `0.20.1`. This will ensure users of winit have the correct version of image without having to run `cargo update`.

**Comment by sodiumjoe** [comment]
ok, bumped `image` dep.

I'm on macos, but I'm not sure what the second thing is. Just delete that `impl` and update the changelog?

**Comment by francesca64** [comment]
That impl is used internally here: https://github.com/tomaka/winit/blob/0fca8e8cb57f0b4b03bc12b1b17bec5855e7ec7e/src/platform/macos/window.rs#L720

So we either need to prevent the impl from being exposed (if that's possible?) or just change it into a regular `pub(crate)` method. Either way, it should live in the `window` module, since having private stuff in the `os` modules is always a bit confusing.

**Comment by vberger** [comment]
> So we either need to prevent the impl from being exposed (if that's possible?)

I don't think that is possible, unless the type which has the impl is private, of course.

**Comment by sodiumjoe** [comment]
rebased master again, i think that was all the blockers

**Pull request merged**
